// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO7lUU6BWCL7Qu9_-EX68LshBnX4ieUQ8',
    appId: '1:15873041679:web:aad1430da3a6cf07d7ca7a',
    messagingSenderId: '15873041679',
    projectId: 'verifeye-de357',
    authDomain: 'verifeye-de357.firebaseapp.com',
    storageBucket: 'verifeye-de357.appspot.com',
    measurementId: 'G-Y3RXD1N9E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwQuSE2gSo5xhzjWPVwMaIozdFuU2XSI',
    appId: '1:15873041679:android:4bae633ce352cd07d7ca7a',
    messagingSenderId: '15873041679',
    projectId: 'verifeye-de357',
    storageBucket: 'verifeye-de357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLwKL3F57JAxzbzjIs_rj5lPqjlFKgUA',
    appId: '1:15873041679:ios:e5690c0c3b2b41f6d7ca7a',
    messagingSenderId: '15873041679',
    projectId: 'verifeye-de357',
    storageBucket: 'verifeye-de357.appspot.com',
    iosBundleId: 'com.example.verifeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLwKL3F57JAxzbzjIs_rj5lPqjlFKgUA',
    appId: '1:15873041679:ios:e5690c0c3b2b41f6d7ca7a',
    messagingSenderId: '15873041679',
    projectId: 'verifeye-de357',
    storageBucket: 'verifeye-de357.appspot.com',
    iosBundleId: 'com.example.verifeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO7lUU6BWCL7Qu9_-EX68LshBnX4ieUQ8',
    appId: '1:15873041679:web:ffa6236fab04b1f7d7ca7a',
    messagingSenderId: '15873041679',
    projectId: 'verifeye-de357',
    authDomain: 'verifeye-de357.firebaseapp.com',
    storageBucket: 'verifeye-de357.appspot.com',
    measurementId: 'G-H9ZD2HYLE6',
  );
}
